# Generated by Django 6.0.4 on 2026-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yop', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('specie', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
